steps:
  build-mammamia:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      #dockerfile: ./mammamia/Dockerfile
      #context: ./mammamia
      context: https://github.com/UrloMythus/MammaMia.git#main
      dockerfile: Dockerfile
      repo: registry.oci.w3studio.it/mammamia
      tags: latest, ${CI_COMMIT_SHA}
      push: true
      registry: registry.oci.w3studio.it
      username:
        from_secret: OCI_REGISTRY_USER
      password:
        from_secret: OCI_REGISTRY_PASSWORD
  #build-mfp:
  #  image: woodpeckerci/plugin-docker-buildx:6.0.1
  #  settings:
  #    dockerfile: Dockerfile
  #    context: https://github.com/mhdzumair/mediaflow-proxy.git#main
  #    repo: registry.oci.w3studio.it/media_flow_proxy
  #    tags: latest, ${CI_COMMIT_SHA}
  #    push: true
  #    registry: registry.oci.w3studio.it
  #    username:
  #      from_secret: OCI_REGISTRY_USER
  #    password:
  #      from_secret: OCI_REGISTRY_PASSWORD
  #build-streamv:
  #  image: woodpeckerci/plugin-docker-buildx:6.0.1
  #  settings:
  #    context: https://github.com/qwertyuiop8899/streamvix.git#main
  #    dockerfile: Dockerfile
  #    repo: registry.oci.w3studio.it/streamv
  #    tags: latest, ${CI_COMMIT_SHA}
  #    push: true
  #    registry: registry.oci.w3studio.it
  #    username:
  #      from_secret: OCI_REGISTRY_USER
  #    password:
  #      from_secret: OCI_REGISTRY_PASSWORD
  #build-webstreamr:
  #  image: woodpeckerci/plugin-docker-buildx:6.0.1
  #  settings:
  #    context: "https://github.com/webstreamr/webstreamr.git#main"
  #    dockerfile: Dockerfile
  #    repo: registry.oci.w3studio.it/webstreamr
  #    tags: latest, ${CI_COMMIT_SHA}
  #    push: true
  #    registry: registry.oci.w3studio.it
  #    username:
  #      from_secret: OCI_REGISTRY_USER
  #    password:
  #      from_secret: OCI_REGISTRY_PASSWORD
  
  update-stack:
    image: docker
    environment:
      OCI_REGISTRY_USER:
        from_secret: OCI_REGISTRY_USER
      OCI_REGISTRY_PASSWORD:
        from_secret: OCI_REGISTRY_PASSWORD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "$OCI_REGISTRY_PASSWORD" | docker login registry.oci.w3studio.it -u "$OCI_REGISTRY_USER" --password-stdin
      - docker service update --image registry.oci.w3studio.it/mammamia:${CI_COMMIT_SHA} --with-registry-auth stremio_mammamia
    #  - docker service update --image registry.oci.w3studio.it/media_flow_proxy:${CI_COMMIT_SHA} --with-registry-auth stremio-stack_mediaflow_proxy
    #  - docker service update --image registry.oci.w3studio.it/streamv:${CI_COMMIT_SHA} --with-registry-auth stremio-stack_streamv
    #  - docker service update --image registry.oci.w3studio.it/webstreamr:${CI_COMMIT_SHA} --with-registry-auth stremio_webstreamr
      
      

