version: '3.8'

services:
  easy_proxy:
    #build: https://github.com/realbestia1/EasyProxy#main
    image: ghcr.io/realbestia1/easyproxy:latest
    container_name: easyproxy
    environment:
      - API_PASSWORD=${API_PASSWORD}
      - 'TRANSPORT_ROUTES={"all://*.ichigotv.net": {"verify_ssl": false}, "all://ichigotv.net": {"verify_ssl": false}}'
    restart: unless-stopped
  mediaflow_proxy:
    #build: https://github.com/mhdzumair/mediaflow-proxy.git#main
    image: qwertyuiop8899/mediaflow-proxy:latest
    container_name: mediaflow_proxy
    environment:
      - API_PASSWORD=${API_PASSWORD}
      - 'TRANSPORT_ROUTES={"all://*.ichigotv.net": {"verify_ssl": false}, "all://ichigotv.net": {"verify_ssl": false}}'
      - FORWARDED_ALLOW_IPS=${FORWARDED_ALLOW_IPS}
    restart: unless-stopped
  mammamia:
    #build: https://github.com/UrloMythus/MammaMia.git#main
    image: qwertyuiop8899/mammamia:latest
    container_name: mammamia
    environment:
      - TMDB_KEY=${TMDB_KEY}
      - PROXY=${PROXY}
      - FORWARDPROXY=${FORWARDPROXY}
    restart: unless-stopped 
  #stremio-docker:
  #  image: tsaridas/stremio-docker:latest
  #  container_name: stremio-docker
  #  ports:
  #    - "8080:8080"
  #    - "11470:11470"
  #  environment:
  #    - NO_CORS=1
  #    - CASTING_DISABLED=1
  #  restart: unless-stopped
  streamv:
    #build: https://github.com/qwertyuiop8899/streamvix.git#main
    image: qwertyuiop8899/streamvix:latest
    container_name: streamv
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - MFP_URL=${MFP_URL}
      - MFP_PSW=${MFP_PSW}
      - BOTHLINK=${BOTHLINK}
      - ANIMEUNITY_ENABLED=${ANIMEUNITY_ENABLED}
      - ANIMESATURN_ENABLED=${ANIMESATURN_ENABLED}
      - ADDON_BASE_URL=${ADDON_BASE_URL}
    restart: unless-stopped 
    command: pnpm start
  easystreams:
    build: https://github.com/realbestia1/easystreams.git#main
    container_name: easystreams
    # ports:
      # - "7000:7000"
    environment:
      - PORT=7000
      - NODE_ENV=production
      - VERBOSE_LOGS=0
      - QUIET_PROVIDER_LOGS=1
      # - CF_PROXY_URL=https://********.workers.dev/
    restart: unless-stopped
  tvvoo:
    #build: https://github.com/realbestia1/easystreams.git#main
    image: qwertyuiop8899/tvvoo:latest
    container_name: tvvoo
    # ports:
      # - "3000:3000"
    restart: unless-stopped
  #webstreamr:
  #  build: https://github.com/webstreamr/webstreamr.git#main
  #  container_name: webstreamr
  #  restart: unless-stopped
networks:
  default:
    external: true
    name: ix-nginx-proxy-manager_default
